src/TriCodeTest/Controllers/CustomerMenuController.cs
// ***********************************************************************
// Assembly         : TriCodeTest
// Author           : noelrodriguez
// Created          : 03-05-2017
//
// Last Modified By : cosmost
// Last Modified On : 03-08-2017
// ***********************************************************************
// <copyright file="CustomerMenuController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TriCodeTest.Data;
using TriCodeTest.Models;
using TriCodeTest.Models.CustomerMenuViewModels;
using TriCodeTest.Models.MenuModels;
using TriCodeTest.Models.OrderModels;
using Newtonsoft.Json;
using TriCodeTest.TwilioNotification;

namespace TriCodeTest.Controllers
{
    /// <summary>
    /// Customer controller class
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize]
    public class CustomerMenuController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private readonly ApplicationDbContext _context;
        /// <summary>
        /// The user manager
        /// </summary>
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerMenuController" /> class.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <param name="userManager">The user manager.</param>
        public CustomerMenuController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// Receives all items needed to build the menu from the database and returns them as an object with lists
        /// </summary>
        /// <returns>View containing list of categories, subcategories, and menu items</returns>
        // GET: CustomerMenu
        public IActionResult Index()
        {
            LoadMenuViewModel LoadMenuViewModel = new LoadMenuViewModel()
            {
                Categories = _context.Category.ToList(),
                Subcategories = _context.Subcategory.ToList(),
                MenuItems = _context.MenuItem.Include(mi => mi.MenuItemIngredients).ThenInclude(mi => mi.Ingredient).ToList()
            };
            return View(LoadMenuViewModel);
        }

        /// <summary>
        /// Returns a view with the order of the current logged in user
        /// </summary>
        /// <returns>View to show items in cart</returns>
        // GET: CustomerMenu/Cart
        public async Task<IActionResult> Cart()
        {
            var user = await GetCurrentUserAsync();
            var cart = await _context.OrderInfo.Where(usr => usr.User.Id == user.Id).Where(s => s.Status == Models.Status.Cart).SingleOrDefaultAsync();
            if (cart != null)
            {
                return View(OrderDeserialize(cart));
            }
            cart = AddNewOrderToDatabase(user);
            return View(OrderDeserialize(cart));
        }

        /// <summary>
        /// Adds single menu item to cart
        /// </summary>
        /// <param name="id">Id of the item being added</param>
        /// <returns>Redirects user to cart</returns>
        // POST: CustomerMenu/PostMenuItemToCart/5
        public async Task<IActionResult> PostMenuItemToCart(int id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            MenuItem menuItem = await _context.MenuItem.Include(ing => ing.MenuItemIngredients).ThenInclude(ing => ing.Ingredient).SingleOrDefaultAsync(mi => mi.Id == id);
            OrderInfo cart = await _context.OrderInfo.Where(usr => usr.User.Id == user.Id).Where(s => s.Status == Models.Status.Cart).SingleOrDefaultAsync();
            Subcategory subcategory = await _context.Subcategory.Include(a => a.AddOns).SingleOrDefaultAsync(s => s.Id == menuItem.SubcategoryId);

            if (cart == null)
            {
                cart = AddNewOrderToDatabase(user);
            }
            // Adds menu item to the Order(Cart)
            CartOrder viewModelCart = OrderDeserialize(cart);
            viewModelCart.CartOrderMenuItems.Add(ConvertToOrderMenuItem(menuItem, subcategory));
            cart.OrderMenuItems = OrderSerialize(viewModelCart).OrderMenuItems;
            cart.TotalPrice += menuItem.Price;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(CustomerMenuController.Cart), "CustomerMenu", null);
        }

        /// <summary>
        /// Returns view containing item passed in to be able to edit it
        /// </summary>
        /// <param name="id">Id of item to edit</param>
        /// <returns>View to edit single item</returns>
        // GET: CustomerMenu/EditItem/5
        public async Task<IActionResult> EditItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await GetCurrentUserAsync();
            List<CartOrderMenuItem> listOfMenuitems = OrderDeserialize(await _context.OrderInfo.Where(usr => usr.User.Id == user.Id)
                .Where(s => s.Status == Models.Status.Cart).SingleOrDefaultAsync()).CartOrderMenuItems;
            foreach (var menuitem in listOfMenuitems)
            {
                if (menuitem.MenuItem.Id == id)
                {
                    if (menuitem.AddOns == null)
                    {
                        menuitem.AddOns = new List<AddOn>();
                    }
                    return View(menuitem);
                }
            }
                
            return RedirectToAction(nameof(CustomerMenuController.Cart), "CustomerMenu", null);
        }

        /// <summary>
        /// Updates the edited item in the database
        /// </summary>
        /// <param name="item">Entire item with changes in addons or ingredients</param>
        /// <returns>True or false if item was successfully updated</returns>
        // POST: CustomerMenu/EditItem/5
        [HttpPost]
        public async Task<ActionResult> EditItem(CartOrderMenuItem item)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            OrderInfo cart = await _context.OrderInfo.Where(usr => usr.User.Id == user.Id)
                .Where(s => s.Status == Models.Status.Cart).SingleOrDefaultAsync();
            CartOrder viewModelCart = OrderDeserialize(cart);

            if (ModelState.IsValid)
            {
                //CartOrderMenuItem menuitem = viewModelCart.CartOrderMenuItems.Find(i => i.MenuItem.Id == item.MenuItem.Id);
                //menuitem.MenuItem.MenuItemIngredients = item.MenuItem.MenuItemIngredients;
                viewModelCart.TotalPrice = 0;
                foreach (var menuitem in viewModelCart.CartOrderMenuItems)
                {
                    if (menuitem.MenuItem.Id == item.MenuItem.Id)
                    {
                        menuitem.MenuItem.MenuItemIngredients = item.MenuItem.MenuItemIngredients;
                        menuitem.AddOns = item.AddOns;
                        menuitem.MenuItem.Size = item.MenuItem.Size;
                    }
                    // Calculate total price
                    viewModelCart.TotalPrice += menuitem.MenuItem.Price;
                    if (menuitem.AddOns != null)
                    {
                        foreach (var addon in menuitem.AddOns)
                        {
                            viewModelCart.TotalPrice += addon.Price;
                        }
                    }
                }
                OrderInfo temp = OrderSerialize(viewModelCart);
                cart.OrderMenuItems = temp.OrderMenuItems;
                cart.TotalPrice = temp.TotalPrice;
                await _context.SaveChangesAsync();
                return Json(true);
            }
            return Json(false);
        }

        /// <summary>
        /// Removes passed item from user's cart
        /// </summary>
        /// <param name="item">Item to remove from cart</param>
        /// <returns>True or false if item was successfully removed from cart</returns>
        [HttpPost]
        public async Task<ActionResult> RemoveItem(CartOrderMenuItem item)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            OrderInfo cart = await _context.OrderInfo.Where(usr => usr.User.Id == user.Id)
                .Where(s => s.Status == Models.Status.Cart).SingleOrDefaultAsync();
            CartOrder viewModelCart = OrderDeserialize(cart);

            if (ModelState.IsValid)
            {
                foreach (var menuitem in viewModelCart.CartOrderMenuItems)
                {
                    if (menuitem.MenuItem.Id == item.MenuItem.Id)
                    {
                        viewModelCart.CartOrderMenuItems.Remove(menuitem);
                        break;
                    }
                }
                OrderInfo temp = OrderSerialize(viewModelCart);
                cart.OrderMenuItems = temp.OrderMenuItems;
                cart.TotalPrice = CalculateTotalPrice(viewModelCart);
                await _context.SaveChangesAsync();
                return Json(true);
            }
            return Json(false);
        }

        /// <summary>
        /// Submits the order and changes it's status from Cart to Received
        /// </summary>
        /// <param name="order">Order containing menu items</param>
        /// <returns>True or false if successfully submitted order</returns>
        // POST: CustomerMenu/SubmitOrder/{OrderObject}
        [HttpPost]

src/TriCodeTest/Controllers/HistoryController.cs
// ***********************************************************************
// Assembly         : TriCodeTest
// Author           : Alex
// Created          : 03-05-2017
//
// Last Modified By : cosmost
// Last Modified On : 03-08-2017
// ***********************************************************************
// <copyright file="HistoryController.cs" company="">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TriCodeTest.Data;
using TriCodeTest.Models.OrderModels;
using Microsoft.EntityFrameworkCore;
using TriCodeTest.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Newtonsoft.Json;

namespace TriCodeTest.Controllers
{
    /// <summary>
    /// Class history
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class HistoryController : Controller
    {

        /// <summary>
        /// The context
        /// </summary>
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Order function
        /// </summary>
        /// <value>The orders.</value>
        public List<OrderInfo> Orders { get; private set; }
        /// <summary>
        /// Controller
        /// </summary>
        /// <param name="context">context</param>
        public HistoryController(ApplicationDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Display list of completed orders.
        /// </summary>
        /// <returns>Index</returns>
        //return the view
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);//current users id
            var userOrders = await _context.OrderInfo.Where(o => o.User.Id == userId && o.Status == Status.Completed).ToListAsync();
            List<Order> orders = ListOrderDeserialize(userOrders);

            //return view with the orders selected
            return View(orders);
        }
        /// <summary>
        /// Displays order details based on clicked order
        /// </summary>
        /// <param name="id">id</param>
        /// <returns>View with details for order</returns>
        public async Task<IActionResult> Details(int? id)
        {
            //return error if no user can be found
            if (id == null)
            {
                return NotFound();
            }//end notFound

            //variable to hold the variable that was in the table cell
            var theOrder = await _context.OrderInfo.Include(usr => usr.User).SingleOrDefaultAsync(m => m.Id == id);
            Console.WriteLine(theOrder.OrderMenuItems);

            var theOrderDS = OrderDeserialize(theOrder);

            //var theOrderDS = OrderDeserialize(theOrder);

            //return error if no order can be found
            if (theOrder == null)
            {
                return NotFound();
            }//end notFound

            return View(theOrderDS);
        }
        /// <summary>
        /// Resets the order state to received and the DateTime to the current time
        /// </summary>
        /// <param name="id">id</param>
        /// <returns>Index view with the updated order</returns>
        [HttpPost]
        public IActionResult resubmitOrder(int? id)
        {
            HistoryViewModel model = new HistoryViewModel();
            {
                Orders = _context.OrderInfo.ToList();
            };
            if (ModelState.IsValid)
            {
                //cast int as a status to set the status
                int newStat = 1;
                Status newStatus;
                newStatus = (Status)newStat;

                //grab the order in question
                var userOrder = Orders.Where(o => o.Id == id).FirstOrDefault();
                DateTime rightNow = DateTime.Now;
                userOrder.DateTime = rightNow;
                userOrder.Status = newStatus;

                //save changes in try/catch block
                try
                {
                    var userId3 = this.User.FindFirstValue(ClaimTypes.NameIdentifier);//current users id
                    var userOrders3 = _context.OrderInfo.Where(o => o.User.Id == userId3).ToListAsync();
                    _context.SaveChanges();
                    return RedirectToAction("Index", userOrders3);
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }

                //userId and users orders for returning to the index page
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);//current users id
                var userOrders = _context.OrderInfo.Where(o => o.User.Id == userId).ToListAsync();

                return RedirectToAction("Index", userOrders);
            }

            //userId and users orders for returning to the index page
            var userId2 = this.User.FindFirstValue(ClaimTypes.NameIdentifier);//current users id
            var userOrders2 = _context.OrderInfo.Where(o => o.User.Id == userId2).ToListAsync();

            return RedirectToAction("Index", userOrders2);
        }

        /// <summary>
        /// Deserialize all the Orders in the database to view models.
        /// </summary>
        /// <param name="listOrderInfo">List of order models from the database</param>
        /// <returns>List of view models of orders with deserialized JSON for items in orders</returns>
        private List<Order> ListOrderDeserialize(List<OrderInfo> listOrderInfo)
        {
            List<Order> ListOrders = new List<Order>();
            foreach (OrderInfo oi in listOrderInfo)
            {
                Order OrderModel = new Order
                {
                    Id = oi.Id,
                    User = oi.User,
                    DateTime = oi.DateTime,
                    Status = oi.Status,
                    TotalPrice = oi.TotalPrice,
                };
                List<OrderMenuItem> OrderMenuItems = JsonConvert.DeserializeObject<List<OrderMenuItem>>(oi.OrderMenuItems);

                OrderModel.OrderMenuItems = OrderMenuItems;
                ListOrders.Add(OrderModel);
                //var orderNames = ListOrders.Select(n => n.OrderMenuItems.Select(p => p.MenuItem.Name));
            }
            return ListOrders;
        }

        /// <summary>
        /// Deserialized an Order and converts it to the view model.
        /// </summary>
        /// <param name="model">Order model from the database</param>
        /// <returns>View model of order with deserialized JSON for items in order</returns>
        private Order OrderDeserialize(OrderInfo model)
        {
            Order OrderModel = new Order
            {
                Id = model.Id,
                User = model.User,
                DateTime = model.DateTime,
                Status = model.Status,
                TotalPrice = model.TotalPrice,
                UserId = model.User.Id
            };
            List<OrderMenuItem> OrderMenuItems = JsonConvert.DeserializeObject<List<OrderMenuItem>>(model.OrderMenuItems);
            OrderModel.OrderMenuItems = OrderMenuItems;
            return OrderModel;
        }
    }
}

src/TriCodeTest/Views/CustomerMenu/Index.cshtml
@model TriCodeTest.Models.CustomerMenuViewModels.LoadMenuViewModel
@using Newtonsoft.Json

@{
    ViewData["Title"] = "Customer Menu";
    // Pre-loads the _CustomerLayout partial view since customers and staff views are significantly different
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

@* This will need to be moved to a separate linked style sheet under ~/css/*@
<style>
.featured-item-image {
    max-width: 100%;
    height: auto;
    width: auto\9;
}
.banner-img {
    margin-left: auto;
    margin-right: auto;
    display: block;
    max-width: 100%;
}
</style>

@* Categories Page *@

<div data-role="page" id="categories-page">
    @* Panel *@
    <div data-role="panel" class="myPanel" id="category-page-panel" data-position="right">
        <ul id="sidebar" style="list-style-type:none;padding-left:0">
            <li>
                <button class="btn btn-link navbar-btn navbar-link" onclick="location.href='@Url.Action("Cart", "CustomerMenu")'">Cart</button>
            </li>
            <li>
                <button class="btn btn-link navbar-btn navbar-link" onclick="location.href='@Url.Action("Index", "History")'">Order History</button>
            </li>
            @await Html.PartialAsync("_CustomerLoginPartial")
        </ul>
    </div>
    @* Header *@
    <div data-role="header" class="header-navbar">
        <a href="" style="display:none"></a>
        <a href="#category-page-panel" data-role="button" data-icon="bars">
            Menu
        </a>
        <h3>
            <a href="#categories-page" style="color:inherit;text-decoration:none">Food Order</a>
        </h3>
    </div>
    @* Main Content *@
    <div role="main" class="ui-content">
        <div class="featured-item-image">
            <img src="~/images/category-food-banner.jpeg" class="banner-img"/>
        </div>
        <ul id="categoryList" data-role="listview">
            @foreach (var category in Model.Categories)
            {
                <li onclick="loadSubcategories(@JsonConvert.SerializeObject(category))">
                    <a href="#"><h2>@category.Name</h2><p>@category.Description</p></a>
                </li>
            }
        </ul>
    </div>
</div>

@* Subcategories Page *@

<div data-role="page" id="subcategories-page">
    @* Panel *@
    <div data-role="panel" class="myPanel" id="subcategory-page-panel" data-position="right">
        <ul id="sidebar" style="list-style-type:none;padding-left:0">
            <li>
                <button class="btn btn-link navbar-btn navbar-link" onclick="location.href='@Url.Action("Cart", "CustomerMenu")'">Cart</button>
            </li>
            <li>
                <button class="btn btn-link navbar-btn navbar-link" onclick="location.href='@Url.Action("Index", "History")'">Order History</button>
            </li>
            @await Html.PartialAsync("_CustomerLoginPartial")
        </ul>
    </div>
    @* Header *@
    <div data-role="header" class="header-navbar">
        <a href="#" data-rel="back" data-role="button">Back</a>
        <a href="#subcategory-page-panel" data-role="button" data-icon="bars">
            Menu
        </a>
        <h3>
            <a href="#categories-page" style="color:inherit;text-decoration:none">Food Order</a>
        </h3>
    </div>
    @* Main Content (gets loaded dynamically) *@
    <div role="main" class="ui-content">
        <div class="featured-item-image">
            <img src="~/images/subcategory-food-banner.jpg" class="banner-img" />
        </div>
        <ul id="subcategoryList" data-role="listview"></ul>
    </div>
</div>

@* Menu Items Page *@

<div data-role="page" id="menuitems-page">
    @* Panel *@
    <div data-role="panel" class="myPanel" id="menuitem-page-panel" data-position="right">
        <ul id="sidebar" style="list-style-type:none;padding-left:0">
            <li>
                <button class="btn btn-link navbar-btn navbar-link" onclick="location.href='@Url.Action("Cart", "CustomerMenu")'">Cart</button>
            </li>
            <li>
                <button class="btn btn-link navbar-btn navbar-link" onclick="location.href='@Url.Action("Index", "History")'">Order History</button>
            </li>
            @await Html.PartialAsync("_CustomerLoginPartial")
        </ul>
    </div>
    @* Header *@
    <div data-role="header" class="header-navbar">
        <a href="#" data-rel="back" data-role="button">Back</a>
        <a href="#menuitem-page-panel" data-role="button" data-icon="bars">
            Menu
        </a>
        <h3>
            <a href="#categories-page" style="color:inherit;text-decoration:none">Food Order</a>
        </h3>
    </div>
    @* Main Content (gets loaded dynamically) *@
    <div role="main" class="ui-content">
        <ul id="menuitemList" data-role="listview"></ul>
    </div>
</div>

@section Scripts
{
<script>
    // Gloval variable to see data of the page's Model in inspector in JSON format
    /// <var>The loaded data</var>
    var loadedData = @Html.Raw(JsonConvert.SerializeObject(Model));

    // Makes sure to refresh the listview in the panel in the categories page (NOT REALLY NEEDED)
    //$(document).on("pageinit", "#subcategories-page", function() {
    //    $(":mobile-pagecontainer").pagecontainer("change", "#categories-page", {
    //        transition: 'slide'
    //    });
    //});

    function loadSubcategories(category){
        /// <summary>
        /// Loads the subcategories.
        /// </summary>
        /// <param name="category">The category.</param>
        var list = $("#subcategoryList");
        list.empty();
        for (var i = 0; i < category.Subcategories.length; i++){
            var subcategory = category.Subcategories[i];
            list.append("<li onclick='loadMenuitems(" + JSON.stringify(subcategory) + ")'><a href='#'><h2>" + subcategory.Name + "</h2><p>" + subcategory.Description + "</p></a></li>");
        }
        $(":mobile-pagecontainer").pagecontainer("change", "#subcategories-page", {
            transition: 'slide'
        });
    }

    $(document).on("pagebeforeshow", "#subcategories-page", function() {
        /// <summary>
        /// Refreshes the subcategory list before page loads to format it to jquery mobile
        /// </summary>
        $("#subcategoryList").listview("refresh");
        if($("#subcategoryList").is(":empty")){
            $(":mobile-pagecontainer").pagecontainer("change", "#categories-page", {
            });
        }
    });


    function loadMenuitems(subcategory){
        /// <summary>
        /// Loads the menuitems.
        /// Dynamically loads menu items based on subcategory chosen
        /// </summary>
        /// <param name="subcategory">The subcategory.</param>
        var list = $("#menuitemList");
        list.empty();
        for (var i = 0; i < subcategory.MenuItems.length; i++){
            var menuitem = subcategory.MenuItems[i];
            list.append("<li onclick='loadDetails(" + JSON.stringify(menuitem) + ")'><a href='#'><h2>" + menuitem.Name + "</h2><p>" + menuitem.Description + "</p></a></li>");
        }
        $(":mobile-pagecontainer").pagecontainer("change", "#menuitems-page", {
            transition: 'slide'
        });
    }

    $(document).on("pagebeforeshow", "#menuitems-page", function() {
        /// <summary>
        /// Refreshes the menu items list before page loads to format it to jquery mobile
        /// </summary>
        $("#menuitemList").listview("refresh");
        if($("#menuitemList").is(":empty")){

            $(":mobile-pagecontainer").pagecontainer("change", "#categories-page", {
            });
        }
    });


    function loadDetails(menuitem){
        /// <summary>
        /// Loads the details.
        /// Dynamically loads details of menu item (THIS MIGHT NOT BE NEEDED IF WE DO IT LIKE STARBUCKS)
        /// </summary>
        /// <param name="menuitem">The menuitem.</param>
        console.log(menuitem);
        var URL = '@Url.Action("PostMenuItemToCart", "CustomerMenu")' + menuitem.Id;
        window.location = '@Url.Action("PostMenuItemToCart", "CustomerMenu")' + '/' + menuitem.Id;
        @*$.ajax({
            url: '@Url.Action("PostMenuItemToCart", "CustomerMenu")',
            type: 'POST',
            data: JSON.stringify(menuitem),
            contentType: 'aplication/json',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            success: function(response){
                //if (response == 'True'){
                //    location.reload();
                //}
                console.log(response);
            },
            error: function(error){
                x = error;
            }
        });*@
        @*@{ var test = JsonConvert.DeserializeObject(@:menuitem);
            Url.Action("PostMenuItemToCart", "CustomerMenu");}*@
        //var descriptionText = $("#description-text");
        //descriptionText.empty();
        //descriptionText.append(menuitem.Description);
        //$(":mobile-pagecontainer").pagecontainer("change", "#details-page", {
        //    transition: 'slide'
        //});
    }
</script>
}