src/TriCodeTest/Controllers/OrderInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TriCodeTest.Data;
using TriCodeTest.Models.OrderModels;
using Newtonsoft.Json;
using Microsoft.Extensions.Logging;
using TriCodeTest.TwilioNotification;

namespace TriCodeTest.Controllers
{
    /// <summary>
    /// Order info class
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize(Roles = "Admin, Staff")]
    public class OrderInfoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;

        /// <summary>
        /// Order info constructor
        /// </summary>
        /// <param name="context">context</param>
        /// <param name="loggerFactory">loggerFactory</param>
        public OrderInfoController(ApplicationDbContext context, ILoggerFactory loggerFactory)
        {
            _context = context;
            _logger = loggerFactory.CreateLogger<OrderInfoController>();
        }
        /// <summary>
        /// Retrieves all orders in the DB and returns them as a list.
        /// </summary>
        /// <returns>
        /// View containing list of orders
        /// </returns>
        // GET: OrderInfo
        public async Task<IActionResult> Index()
        {
            Order singleOrder = new Order();
            var allOrderInfos = await _context.OrderInfo.Include(oi => oi.User).Where(s => s.Status != Models.Status.Cart && s.Status != Models.Status.Completed).GroupBy(s => s.Status).SelectMany(oi => oi).ToListAsync();
            List<Order> orders = ListOrderDeserialize(allOrderInfos);
            return View(orders);
        }

        /// <summary>
        /// Returns a single Order by the Id passed in.
        /// </summary>
        /// <param name="id">Id of an order</param>
        /// <returns>
        /// View to edit single order
        /// </returns>
        // GET: OrderInfo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var orderInfo = await _context.OrderInfo.Include(usr => usr.User).SingleOrDefaultAsync(m => m.Id == id);
            if (orderInfo == null)
            {
                return NotFound();
            }
            var order = OrderDeserialize(orderInfo);
            return View(order);
        }

        /// <summary>
        /// Will update the Order in the database with the new status passed in.
        /// </summary>
        /// <param name="id">Id of an order</param>
        /// <param name="order">Order object passed in by form</param>
        /// <returns>
        /// Redirect to Index view upon success or editable view of same order object on failure
        /// </returns>
        // POST: OrderInfo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateTime,OrderMenuItems,Status,TotalPrice,UserId")] Order order)
        {
            OrderInfo orderInfo = OrderSerialize(order);
            var numberToSms = _context.Users.SingleOrDefault(usr => usr.Id == order.UserId).PhoneNumber;
            bool success;
            if (id != orderInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.OrderInfo.Attach(orderInfo);
                    var entry = _context.Entry(orderInfo);
                    entry.Property(s => s.Status).IsModified = true;
                    await _context.SaveChangesAsync();

                    if (order.Status.Equals(Models.Status.Pick_Up))
                    {
                        try
                        {
                            success = Notification.SendNotification(numberToSms, "Your order is ready for pickup. DO NOT REPLY! Data rates may apply");
                            ViewBag.Messag = "PhoneNumber incorrect ";
                            if (success)
                            {
                                //ViewBag.Message = "Message sent";
                                return RedirectToAction("Index");
                            }
                        }
                        catch (Exception e)
                        {
                            _logger.LogWarning(e.Message);
                            return View(order);
                        }
                    }
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderInfoExists(orderInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(order);
        }

        /// <summary>
        /// Returns if the Order exists or not.
        /// </summary>
        /// <param name="id">Id of an order</param>
        /// <returns>
        /// order item
        /// </returns>
        private bool OrderInfoExists(int id)
        {
            return _context.OrderInfo.Any(e => e.Id == id);
        }

        /// <summary>
        /// Deserialize an Order and converts it to the view model.
        /// </summary>
        /// <param name="model">Order model from the database</param>
        /// <returns>
        /// View model of order with deserialized JSON for items in order
        /// </returns>
        private Order OrderDeserialize(OrderInfo model)
        {
            Order OrderModel = new Order
            {
                Id = model.Id,
                User = model.User,
                DateTime = model.DateTime,
                Status = model.Status,
                TotalPrice = model.TotalPrice,
                UserId = model.User.Id
            };
            List<OrderMenuItem> OrderMenuItems = JsonConvert.DeserializeObject<List<OrderMenuItem>>(model.OrderMenuItems);
            OrderModel.OrderMenuItems = OrderMenuItems;
            return OrderModel;
        }

        /// <summary>
        /// Serializes a view model and converts it to an Order.
        /// </summary>
        /// <param name="model">Order view model</param>
        /// <returns>
        /// Table model from the database with serialized JSON
        /// </returns>
        private OrderInfo OrderSerialize(Order model)
        {
            OrderInfo OrderInfoModel = new OrderInfo
            {
                Id = model.Id,
                User = model.User,
                DateTime = model.DateTime,
                Status = model.Status,
                TotalPrice = model.TotalPrice,
            };
            string json = JsonConvert.SerializeObject(model.OrderMenuItems);
            OrderInfoModel.OrderMenuItems = json;
            return OrderInfoModel;
        }

        /// <summary>
        /// Deserialize all the Orders in the database to view models.
        /// </summary>
        /// <param name="listOrderInfo">List of order models from the database</param>
        /// <returns>
        /// List of view models of orders with deserialized JSON for items in orders
        /// </returns>
        private List<Order> ListOrderDeserialize(List<OrderInfo> listOrderInfo)
        {
            List<Order> ListOrders = new List<Order>();
            foreach (OrderInfo oi in listOrderInfo)
            {
                Order OrderModel = new Order
                {
                    Id = oi.Id,
                    User = oi.User,
                    DateTime = oi.DateTime,
                    Status = oi.Status,
                    TotalPrice = oi.TotalPrice,
                };
                List<OrderMenuItem> OrderMenuItems = JsonConvert.DeserializeObject<List<OrderMenuItem>>(oi.OrderMenuItems);
                OrderModel.OrderMenuItems = OrderMenuItems;
                ListOrders.Add(OrderModel);
            }
            return ListOrders;
        }
    }
}

src/TriCodeTest/Controllers/UpdateUserRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TriCodeTest.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using TriCodeTest.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TriCodeTest.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize(Roles = "Admin")]
    public class UpdateUserRoleController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateUserRoleController"/> class.
        /// </summary>
        /// <param name="userManager">The user manager.</param>
        /// <param name="roleManager">The role manager.</param>
        /// <param name="context">The context.</param>
        public UpdateUserRoleController(
            UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }
        // GET: /<controller>/
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            UpdateUserRoleViewModel model = new UpdateUserRoleViewModel()
            {
                Users = _userManager.Users.Include(u => u.Roles).ToList(),
                Roles = _roleManager.Roles.ToList()
            };
            var users = _userManager.Users.Include(u => u.Roles).ToList();
            var test = _roleManager.Roles.ToList();
            var roles = _context.Roles.ToList();
            var userRoles = _context.UserRoles.ToList();

            //var roles = _roleManager.Roles.ToList();
            //var roles = _userManager.GetUsersInRoleAsync(users.);

            return View(model);
        }

        /// <summary>
        /// Updates the user role.
        /// </summary>
        /// <param name="userId">The user identifier.</param>
        /// <returns></returns>
        public ActionResult UpdateUserRole(FormCollection userId)
        {
            UpdateUserRoleViewModel model = new UpdateUserRoleViewModel()
            {
                Users = _userManager.Users.Include(u => u.Roles).ToList(),
                Roles = _roleManager.Roles.ToList()
            };

            var users = _userManager.Users.Include(u => u.Roles).ToList();
            // prepopulate roles for the view dropdown
            var list = _context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            var uList = _context.Users.ToList().Select(rr => new SelectListItem { Value = rr.UserName.ToString(), Text = rr.UserName }).ToList();
            ViewBag.Users = uList;

            return View();
        }

        /// <summary>
        /// Sets the role admin.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> setRoleAdmin([FromBody] PostRoleUpdateUserRoleViewModel model)
        {
            var roles = _context.Roles.ToList();
            var users = _context.Users.ToList();
            bool successfullyChanged = false;

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                var userId = user.Id;
                var oldRoleName = await _userManager.GetRolesAsync(user);

                if(!oldRoleName.Contains("Admin"))
                {
                    await _userManager.RemoveFromRoleAsync(user, oldRoleName[0]);
                    await _userManager.AddToRoleAsync(user, "Admin");
                    successfullyChanged = true;
                }

                _context.Entry(user).State = EntityState.Modified;

                return Content(successfullyChanged.ToString());
            }

            return Content(successfullyChanged.ToString());
        }

        /// <summary>
        /// Sets the role staff.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> setRoleStaff([FromBody] PostRoleUpdateUserRoleViewModel model)
        {
            var roles = _context.Roles.ToList();
            var users = _context.Users.ToList();
            bool succcessfullyChanged = false;

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                var userId = user.Id;
                var oldRoleName = await _userManager.GetRolesAsync(user);

                if (!oldRoleName.Contains("Staff"))
                {
                    await _userManager.RemoveFromRoleAsync(user, oldRoleName[0]);
                    await _userManager.AddToRoleAsync(user, "Staff");
                    succcessfullyChanged = true;
                }

                _context.Entry(user).State = EntityState.Modified;

                return Content(succcessfullyChanged.ToString());
            }

            return Content(succcessfullyChanged.ToString());
        }

        /// <summary>
        /// Sets the role customer.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns></returns>
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> setRoleCustomer([FromBody] PostRoleUpdateUserRoleViewModel model)
        {
            var roles = _context.Roles.ToList();
            var users = _context.Users.ToList();
            bool successfullyChanged = false;

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(model.Email);
                var userId = user.Id;
                var oldRoleName = await _userManager.GetRolesAsync(user);

                if (!oldRoleName.Contains("Customer"))
                {
                    await _userManager.RemoveFromRoleAsync(user, oldRoleName[0]);
                    await _userManager.AddToRoleAsync(user, "Customer");
                    successfullyChanged = true;
                }

                _context.Entry(user).State = EntityState.Modified;

                return Content(successfullyChanged.ToString());
            }

            return Content(successfullyChanged.ToString());
        }

        /// <summary>
        /// Roles the add to user.
        /// </summary>
        /// <param name="UserName">Name of the user.</param>
        /// <param name="RoleName">Name of the role.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RoleAddToUser(string UserName, string RoleName)
        {
            var users = _userManager.Users.ToList();
            var roles = _context.Roles.ToList();
            var userRoles = _context.UserRoles.ToList();

            if (ModelState.IsValid)
            {
                // THIS LINE IS IMPORTANT
                var oldUser = await _userManager.FindByNameAsync(UserName);
                var oldUserId = oldUser.Id;
                var oldRoleName = await _userManager.GetRolesAsync(oldUser);
                
                if (!oldRoleName.Contains(RoleName))
                {
                    await _userManager.RemoveFromRoleAsync(oldUser, oldRoleName[0]);
                    await _userManager.AddToRoleAsync(oldUser, RoleName);
                }
                _context.Entry(oldUser).State = EntityState.Modified;

                return RedirectToAction("Index", users);
            }

            return RedirectToAction("Index", users);
        }
    }
}

src/TriCodeTest/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TriCodeTest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
    </environment>
    <environment names="Staging,Production">
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        @* This should be used when deployed 
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />*@
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
    </environment>
</head>
<body>
    @*<div class="navbar navbar-fixed-top navbar-default ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_CustomerLoginPartial")
            </div>
        </div>
    </div>*@
    <div>
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>*@
        @* Only this section should be used when deployed *@
        @*<script src="~/js/site.min.js" asp-append-version="true"></script>*@
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/TriCodeTest/Views/Shared/_CustomerLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TriCodeTest.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" data-ajax="false">
        <li>
            <input type="button" value="Manage Account" onclick="location.href='@Url.Action("Index", "Manage")'" />
        </li>
        <li>
            <button type="submit" class="btn btn-link navbar-btn navbar-link">Log off</button>
        </li>           
    </form>
}
else
{

        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
        <li><a asp-area="" asp-controller="Account" asp-action="Login">Log in</a></li>

}

src/TriCodeTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TriCodeTest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/dist_material/css/bootstrap-material-design.css" />*@
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/dist_material/css/mdb.min.css" />*@

        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-custom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p asp-area="" class="navbar-brand">TriCode</p>
            </div>
            <div class="navbar-collapse collapse"style="color: white;">
                <ul class="nav navbar-nav" >
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="OrderInfo" asp-action="Index">Orders</a></li>
                        <li><a asp-area="" asp-controller="MenuCreation" asp-action="Menu">Menu</a></li>
                        <li><a asp-area="" asp-controller="UpdateUserRole" asp-action="Index">Accounts</a></li>
                    }
                    @if (User.IsInRole("Staff"))
                    {
                        <li><a asp-area="" asp-controller="OrderInfo" asp-action="Index">Orders</a></li>
                    }
                    @if (User.IsInRole("Customer"))
                    {
                        <li><a asp-area="" asp-controller="CustomerMenu" asp-action="Index">Menu</a></li>

                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Food Order</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap/dist/dist_material/js/material.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/TriCodeTest/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TriCodeTest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    </environment>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-default ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="MenuCreation" asp-action="Menu">Account</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/TriCodeTest/Views/Shared/_PanelLayout.cshtml
<li>
    <a class="button" href='@Url.Action("Cart", "CustomerMenu")'>Cart</a>
</li>